#PBS -S /bin/bash
#PBS -N pod-ompi2-ubuntu17
#PBS -j oe
#PBS -q B30
#PBS -l nodes=2:ppn=28
#PBS -l walltime=00:05:00

echo "Job ID: $PBS_JOBID"
echo "Queue:  $PBS_QUEUE"
echo "Cores:  $PBS_NP"
echo "Nodes:  $(cat $PBS_NODEFILE | sort -u | tr '\n' ' ')"

cd $PBS_O_WORKDIR
module load singularity/2.4.2
module load openmpi/2.0.1/gcc.6.2.0

SINGIMG="pod-ompi2-ubuntu17.img"

mpirun singularity exec $SINGIMG /usr/bin/mpi_ring 
exit $?

# vim: syntax=sh:ts=4:sw=4:expandtab
